---
title: Release Notes
format:
  html:
    toc: true
    number-sections: false
---

## v1.1.0

**Breaking changes**

- Add `collect_to_mat` function to replace `dataset55_to_mat` and `dataset58_to_mat` functions. This new function can handle both `Dataset55` and `Dataset58` objects.

## v1.0.2

- Improve internals implementation to deal with files that have inconsistent line header.

- Implementation of tests to check for correct reading and writing of the supported datasets.

## v1.0.1

- Minor changes to the internals to avoid errors when reading files.

## v1.0.0

**Breaking changes**

- Refactoring of the code to reduce the memory footprint when parsing UFF files.

- Add `supported_file_extensions` function to list supported UFF file extensions.

- Add `srdc_doc` function to access to the original documentation for supported datasets.

- `readuff` and `writeuff` functions now check the file extension and throw an error if it is not supported.

- Datasets
  - Add `Dataset1858`. Thanks to [@JakeZw](https://github.com/Spectrum-Tec) for submitting the PR.

  - `readuff` and `writeuff` now can now read and write binary `Dataset58`. Thanks to [@JakeZw](https://github.com/Spectrum-Tec) for submitting the PR.

  - `conversion_factors` field in `Dataset164` struct has been modified in favor of individual names for scaling factors. This change improves fields clarity. Thanks to [@JakeZw](https://github.com/Spectrum-Tec) for submitting the PR.

  - `node_coords` field in `Dataset15` struct has been changed from `Vector{Vector{Float64}}` to `Matrix{Float64}` for easier manipulation of node coordinates and consistency with `Dataset2411`.


## v0.2.1

**Internals changes only**

- Skipping unsupported dataset blocks during UFF file parsing, with a warning message instead of throwing an error.

- Remove `parse_dataset` function in favor of `getfield(UFFFiles, Symbol("parse_dataset", dtype))` calls in `read_uff` function. Thanks to [@JakeZw](https://github.com/Spectrum-Tec)

- Modify `parse_dataset58` to handle lines without spacing between values.

- Use multiple dispatch to write dataset blocks in a more modular way.

## v0.2.0

- Implementation of writing functionality for all the datasets in the package.

## v0.1.0

- Initial release of the package